# Generated by Django 3.2.2 on 2021-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100, null=True),
        ),
    ]
