# Generated by Django 3.2.2 on 2021-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
