# Generated by Django 3.2.2 on 2021-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchList_movie_id',
            new_name='movie_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
